# Generated by Django 3.0.7 on 2020-08-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='display_name',
            field=models.CharField(default='anonymous user', max_length=150),
        ),
    ]
