# Generated by Django 3.0.7 on 2020-08-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
