# Generated by Django 3.0.7 on 2020-06-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200629_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address1',
            field=models.CharField(max_length=1024, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(max_length=1024, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=1024, verbose_name='City'),
        ),
    ]
