# Generated by Django 3.0.7 on 2020-07-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200629_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_requester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
