# Generated by Django 3.0.7 on 2020-08-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200809_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fullname_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
