# Generated by Django 3.0.7 on 2020-08-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200810_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
