# Generated by Django 3.0.7 on 2020-08-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_location_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullname_privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_privacy',
            field=models.BooleanField(default=True),
        ),
    ]
