# Generated by Django 3.0.7 on 2020-08-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200810_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_privacy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fullname_privacy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location_privacy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_privacy',
        ),
    ]
