# Generated by Django 3.0.7 on 2020-08-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200810_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fullname_privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_privacy',
            field=models.BooleanField(default=True),
        ),
    ]
