# Generated by Django 3.0.7 on 2021-02-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201004_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
