# Generated by Django 3.0.7 on 2021-02-11 23:14

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_stripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.file_path),
        ),
    ]
