# Generated by Django 3.0.7 on 2021-01-06 01:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
