language: python
python:
  - "3.9"
cache: pip
install:
  - pip install -r requirements.txt
env:
  - SECRET_KEY=totalllyfake DEBUG=0 EMAIL_BACKEND=django.core.mail.backends.dummy.EmailBackend PUBLIC_URL=https://skcema.org/
script:
  - python manage.py test
  - echo "replace me with a linter!"
