# Generated by Django 3.0.7 on 2020-08-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0004_request_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='admin_notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='admin_notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='items_list',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='request',
            name='special_info',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
