# Generated by Django 3.0.7 on 2020-08-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0005_auto_20200823_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='locations',
            field=models.CharField(choices=[('Algona Pacific', 'Algona Pacific'), ('Auburn', 'Auburn'), ('Bellevue', 'Bellevue'), ('Bothell', 'Bothell'), ('Burien', 'Burien'), ('Carnation', 'Carnation'), ('Covington', 'Covington'), ('Des Moines', 'Des Moines'), ('Duvall', 'Duvall'), ('Fall City', 'Fall City'), ('Federal Way', 'Federal Way'), ('High Line', 'High Line'), ('Issaquah', 'Issaquah'), ('Kenmore', 'Kenmore'), ('Kent', 'Kent'), ('Kirkland', 'Kirkland'), ('Maple Valley', 'Maple Valley'), ('Newcastle', 'Newcastle'), ('Normandy Park', 'Normandy Park'), ('North Bend', 'North Bend'), ('Puyallup', 'Puyallup'), ('Redmond', 'Redmond'), ('Renton', 'Renton'), ('SeaTac', 'SeaTac'), ('Sammamish', 'Sammamish'), ('Snoqualmie', 'Snoqualmie'), ('Sumner', 'Sumner'), ('Tukwila', 'Tukwila'), ('White Center', 'White Center'), ('Woodinville', 'Woodinville')], max_length=1024),
        ),
    ]
