# Generated by Django 3.0.7 on 2020-08-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0007_auto_20200827_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Support'},
        ),
    ]
