# Generated by Django 3.0.7 on 2020-09-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0010_volunteer_skip_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='address1',
            field=models.CharField(max_length=100, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='request',
            name='address2',
            field=models.CharField(blank=True, max_length=25, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(max_length=35, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='request',
            name='contact_preference',
            field=models.CharField(choices=[('Call', 'Phone Number - Call'), ('Text', 'Phone Number - Text'), ('Email', 'Email')], max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='financial_support',
            field=models.CharField(choices=[('Self-Pay and Donate', 'Pay with your own money and donate to support your community members'), ('Self-Pay', 'Pay with your own money (coordinate with delivery person)'), ('Request Support', 'Request support with your delivery items')], max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='locations',
            field=models.CharField(choices=[('Algona Pacific', 'Algona Pacific'), ('Auburn', 'Auburn'), ('Bellevue', 'Bellevue'), ('Bothell', 'Bothell'), ('Burien', 'Burien'), ('Carnation', 'Carnation'), ('Covington', 'Covington'), ('Des Moines', 'Des Moines'), ('Duvall', 'Duvall'), ('Fall City', 'Fall City'), ('Federal Way', 'Federal Way'), ('High Line', 'High Line'), ('Issaquah', 'Issaquah'), ('Kenmore', 'Kenmore'), ('Kent', 'Kent'), ('Kirkland', 'Kirkland'), ('Maple Valley', 'Maple Valley'), ('Newcastle', 'Newcastle'), ('Normandy Park', 'Normandy Park'), ('North Bend', 'North Bend'), ('Puyallup', 'Puyallup'), ('Redmond', 'Redmond'), ('Renton', 'Renton'), ('Sammamish', 'Sammamish'), ('SeaTac', 'SeaTac'), ('Snoqualmie', 'Snoqualmie'), ('Sumner', 'Sumner'), ('Tukwila', 'Tukwila'), ('White Center', 'White Center'), ('Woodinville', 'Woodinville')], max_length=35, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='request',
            name='need_checkin',
            field=models.CharField(choices=[('Text', 'Yes, by text'), ('Phone', 'Yes, by phone'), ('No', 'No, thank you')], max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='zip_code',
            field=models.CharField(max_length=15, verbose_name='ZIP / Postal code'),
        ),
    ]
