# Generated by Django 3.0.7 on 2020-08-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_request_admin_notes'),
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Reviewed'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests.Request', verbose_name='Request'),
        ),
    ]
