# Generated by Django 3.0.7 on 2021-01-01 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_preference', models.CharField(choices=[('Call', 'Phone Number - Call'), ('Text', 'Phone Number - Text'), ('Email', 'Email')], max_length=100)),
                ('locations', models.CharField(choices=[('Algona Pacific', 'Algona Pacific'), ('Auburn', 'Auburn'), ('Bellevue', 'Bellevue'), ('Bothell', 'Bothell'), ('Burien', 'Burien'), ('Carnation', 'Carnation'), ('Covington', 'Covington'), ('Des Moines', 'Des Moines'), ('Duvall', 'Duvall'), ('Fall City', 'Fall City'), ('Federal Way', 'Federal Way'), ('High Line', 'High Line'), ('Issaquah', 'Issaquah'), ('Kenmore', 'Kenmore'), ('Kent', 'Kent'), ('Kirkland', 'Kirkland'), ('Maple Valley', 'Maple Valley'), ('Newcastle', 'Newcastle'), ('Normandy Park', 'Normandy Park'), ('North Bend', 'North Bend'), ('Puyallup', 'Puyallup'), ('Redmond', 'Redmond'), ('Renton', 'Renton'), ('Sammamish', 'Sammamish'), ('SeaTac', 'SeaTac'), ('Snoqualmie', 'Snoqualmie'), ('Sumner', 'Sumner'), ('Tukwila', 'Tukwila'), ('White Center', 'White Center'), ('Woodinville', 'Woodinville')], max_length=35, verbose_name='Location')),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=35, verbose_name='City')),
                ('zip_code', models.CharField(max_length=15, verbose_name='ZIP / Postal code')),
                ('transportation_access', models.CharField(max_length=15)),
                ('walk_distance', models.CharField(max_length=200)),
                ('financial_support', models.CharField(choices=[('Money Upfront', 'No. I will need money ahead of time in order to buy the groceries.'), ('Self-Pay, Need Reimbursement', 'No. I have the money to make the initial purchase, but I will need reimbursement.'), ('Self-Pay, Partially Donate', 'Yes. I have the money to make the initial purchase & can donate some, but I may need reimbursement eventually.'), ('Donate All', 'Yes. I will donate any groceries I pick up.'), ('Other', 'Ohter')], max_length=150)),
                ('special_info', models.TextField(blank=True, max_length=2048)),
                ('additional_supplies', models.CharField(max_length=15)),
                ('need_checkin', models.CharField(choices=[('Text, 2-3 weeks', 'check-in via text once every 2-3 weeks'), ('Text, once a month', 'check-in via text once a month'), ('Phone, 2-3 weeks', 'check-in via phone once every 2-3 weeks'), ('Phone, once a month', 'check-in via phone once a month'), ('Other', 'Other')], max_length=150)),
                ('extra_info', models.TextField(blank=True, max_length=1024)),
                ('ma_pod_setup', models.BooleanField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], default=None, max_length=150)),
                ('support_skills', models.TextField(blank=True, max_length=1024)),
                ('accessibility_needs', models.CharField(choices=[('A buddy to do delivers with', 'A buddy to do delivers with'), ('Help acquiring hand sanitizer/wipes', 'Help acquiring hand sanitizer/wipes'), ('Other', 'Other')], max_length=150)),
                ('availability', models.CharField(choices=[('Mornings', 'Mornings'), ('Afternoons', 'Afternoons'), ('Evening', 'Evening'), ('Weekends', 'Weekends'), ('Other', 'Other')], max_length=150)),
                ('volunteer_hours', models.CharField(max_length=5)),
                ('languages', models.CharField(max_length=200)),
                ('coordinating', models.CharField(choices=[('6hrs/weeks 2hrs/weeks 3months', 'Commit at least 6 hours per week for the first few weeks and then 2 hours or more after for at least three months'), ('Be willing to learn or take training', 'Have an understanding or be willing to learn about transformative justice, abolition, solidarity support, emotional first aid, or take these necessary training within the first couple of weeks of volunteering'), ('Attend weekly meetings and be committed', 'Attend weekly meetings and be committed to continued learning and struggle'), ('Other', 'Other')], max_length=150)),
                ('storage_space', models.CharField(max_length=200)),
                ('pickup_concern', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit', models.CharField(max_length=150, verbose_name='Last edit by')),
                ('admin_notes', models.TextField(blank=True, max_length=1024, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
