# Generated by Django 3.0.7 on 2021-01-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='accessibility_needs',
            field=models.CharField(blank=True, choices=[('A buddy to do delivers with', 'A buddy to do delivers with'), ('Help acquiring hand sanitizer/wipes', 'Help acquiring hand sanitizer/wipes'), ('Other', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='offer',
            name='additional_supplies',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='offer',
            name='availability',
            field=models.CharField(blank=True, choices=[('Mornings', 'Mornings'), ('Afternoons', 'Afternoons'), ('Evening', 'Evening'), ('Weekends', 'Weekends'), ('Other', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='offer',
            name='coordinating',
            field=models.CharField(blank=True, choices=[('6hrs/weeks 2hrs/weeks 3months', 'Commit at least 6 hours per week for the first few weeks and then 2 hours or more after for at least three months'), ('Be willing to learn or take training', 'Have an understanding or be willing to learn about transformative justice, abolition, solidarity support, emotional first aid, or take these necessary training within the first couple of weeks of volunteering'), ('Attend weekly meetings and be committed', 'Attend weekly meetings and be committed to continued learning and struggle'), ('Other', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='offer',
            name='financial_support',
            field=models.CharField(blank=True, choices=[('Money Upfront', 'No. I will need money ahead of time in order to buy the groceries.'), ('Self-Pay, Need Reimbursement', 'No. I have the money to make the initial purchase, but I will need reimbursement.'), ('Self-Pay, Partially Donate', 'Yes. I have the money to make the initial purchase & can donate some, but I may need reimbursement eventually.'), ('Donate All', 'Yes. I will donate any groceries I pick up.'), ('Other', 'Ohter')], max_length=150),
        ),
        migrations.AlterField(
            model_name='offer',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='need_checkin',
            field=models.CharField(blank=True, choices=[('Text, 2-3 weeks', 'check-in via text once every 2-3 weeks'), ('Text, once a month', 'check-in via text once a month'), ('Phone, 2-3 weeks', 'check-in via phone once every 2-3 weeks'), ('Phone, once a month', 'check-in via phone once a month'), ('Other', 'Other')], max_length=150),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pickup_concern',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='storage_space',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='support_skills',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='offer',
            name='walk_distance',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
