# Generated by Django 3.0.7 on 2021-01-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210102_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='locations',
            field=models.CharField(max_length=250, verbose_name='Location'),
        ),
    ]
