# Generated by Django 3.0.7 on 2020-09-27 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_photo', models.ImageField(blank=True, default=None, null=True, upload_to='receipt_photos/%Y/%m/%d/')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('In Process', 'In Process'), ('Completed', 'Completed')], default=None, max_length=150)),
                ('volunteer_notes', models.TextField(blank=True, max_length=1024, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requests.Volunteer', verbose_name='Support ID')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent')], default='Pending', max_length=150)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Donator')),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Reimbursement', verbose_name='Reimbursement ID')),
            ],
        ),
    ]
