# Generated by Django 3.0.7 on 2020-07-31 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0003_auto_20200731_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_photo', models.ImageField(blank=True, default=None, upload_to='')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(default=None, max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requests.Volunteer')),
            ],
        ),
    ]
