# Generated by Django 3.0.7 on 2020-08-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt_photo',
            field=models.ImageField(default=None, null=True, upload_to='receipt_photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Completed', 'Completed')], default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
