# Generated by Django 3.0.7 on 2020-08-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20200801_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='volunteer_notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
