# Generated by Django 3.0.7 on 2020-08-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_reimbursement_volunteer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='receipt_photos/%Y/%m/%d/'),
        ),
    ]
