# Generated by Django 3.0.7 on 2020-08-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0007_auto_20200827_0221'),
        ('funds', '0004_auto_20200824_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supports.Volunteer', verbose_name='Support ID'),
        ),
    ]
