# Generated by Django 3.0.7 on 2021-01-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_auto_20200915_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='unpaid', max_length=150),
        ),
    ]
