# Generated by Django 3.0.7 on 2021-01-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_auto_20210126_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
