# Generated by Django 3.0.7 on 2021-01-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_auto_20210126_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
