# Generated by Django 3.0.7 on 2020-07-20 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('locations', models.CharField(choices=[('Algona Pacific', 'Algona Pacific'), ('Auburn', 'Auburn'), ('Bellevue', 'Bellevue'), ('Bothell', 'Bothell'), ('Burien', 'Burien'), ('Carnation', 'Carnation'), ('Covington', 'Covington'), ('Des Moines', 'Des Moines'), ('Duvall', 'Duvall'), ('Fall City', 'Fall City'), ('Federal Way', 'Federal Way'), ('High Line', 'High Line'), ('Issaquah', 'Issaquah'), ('Kenmore', 'Kenmore'), ('Kent', 'Kent'), ('Kirkland', 'Kirkland'), ('Maple Valley', 'Maple Valley'), ('Newcastle', 'Newcastle'), ('Normandy Park', 'Normandy Park'), ('North Bend', 'North Bend'), ('Puyallup', 'Puyallup'), ('Redmond', 'Redmond'), ('Renton', 'Renton'), ('Sammamish', 'Sammamish'), ('Snoqualmie', 'Snoqualmie'), ('Sumner', 'Sumner'), ('Tukwila', 'Tukwila'), ('White Center', 'White Center'), ('Woodinville', 'Woodinville')], max_length=1024)),
                ('contact_preference', models.CharField(choices=[('Phone Number - Call', 'Phone Number - Call'), ('Phone Number - Text', 'Phone Number - Text'), ('Email', 'Email')], max_length=150)),
                ('prefered_food', models.TextField(max_length=1024)),
                ('items_list', models.TextField()),
                ('food_restrictions', models.TextField(blank=True, default=None)),
                ('household_number', models.SmallIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('In the next 72 hours', 'In the next 72 hours'), ('Over the next few days', 'Over the next few days'), ('Useful if available', 'Useful if avaiable')], max_length=150)),
                ('financial_support', models.CharField(choices=[('Pay with your own money and donate to support your community members', 'Pay with your own money and donate to support your community members'), ('Pay with your own money (coordinate with delivery person)', 'Pay with your own money (coordinate with delivery person)'), ('Request support with your delivery items', 'Request support with your delivery items')], max_length=150)),
                ('special_info', models.TextField(blank=True)),
                ('share_info', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('need_checkin', models.CharField(choices=[('Yes, by text', 'Yes, by text'), ('Yes, by phone', 'Yes, by phone'), ('No, thank you', 'No, thank you')], max_length=150)),
                ('extra_info', models.TextField(blank=True, max_length=1024)),
                ('ma_pod_setup', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, max_length=150)),
                ('offer_resources', models.TextField(blank=True, max_length=1024)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed'), ('Transferred', 'Transferred')], default='New', max_length=150)),
                ('last_edit', models.CharField(max_length=150)),
                ('volunteer_status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Signed Up', 'Signed Up'), ('Delivered', 'Delivered')], default=None, max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requests.Request')),
            ],
        ),
    ]
