# Generated by Django 3.0.7 on 2020-06-29 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('city', models.CharField(choices=[('Algona Pacific', 'Algona Pacific'), ('Auburn', 'Auburn'), ('Bellevue', 'Bellevue'), ('Bothell', 'Bothell'), ('Burien', 'Burien'), ('Carnation', 'Carnation'), ('Covington', 'Covington'), ('Des Moines', 'Des Moines'), ('Duvall', 'Duvall'), ('Fall City', 'Fall City'), ('Federal Way', 'Federal Way'), ('High Line', 'High Line'), ('Issaquah', 'Issaquah'), ('Kenmore', 'Kenmore'), ('Kent', 'Kent'), ('Kirkland', 'Kirkland'), ('Maple Valley', 'Maple Valley'), ('Newcastle', 'Newcastle'), ('Normandy Park', 'Normandy Park'), ('North Bend', 'North Bend'), ('Puyallup', 'Puyallup'), ('Redmond', 'Redmond'), ('Renton', 'Renton'), ('Sammamish', 'Sammamish'), ('Snoqualmie', 'Snoqualmie'), ('Sumner', 'Sumner'), ('Tukwila', 'Tukwila'), ('White Center', 'White Center'), ('Woodinville', 'Woodinville')], max_length=1024)),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('contact_preference', models.CharField(choices=[('CALL', 'Phone Number - Call'), ('TEXT', 'Phone Number -Text'), ('EMAIL', 'Email')], max_length=150)),
                ('prefered_food', models.CharField(choices=[('Ingredients to cook with', 'Ingredients to cook with'), ('Reheat and serve/frozen', 'Reheat and serve/frozen'), ('Low Prep (like sandwiches, pasta)', 'Low Prep (like sandwiches, pasta)'), ('Zero - Prep', 'Zero - Prep')], max_length=150)),
                ('items_list', models.TextField()),
                ('food_restrictions', models.TextField(blank=True, default=None)),
                ('household_number', models.SmallIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('ASAP', 'ASAP'), ('In the next 72 hours', 'In the next 72 hours'), ('Over the next few days', 'Over the next few days'), ('Useful if available', 'Useful if avaiable')], max_length=150)),
                ('financial_support', models.CharField(choices=[('Pay and Donate', 'Pay with your own money and donate to support your community members'), ('Pay', 'Pay with your own money (coordinate with delivery person)'), ('Need Support', 'Request support with your delivery items')], max_length=150)),
                ('special_info', models.TextField(blank=True)),
                ('share_info', models.BooleanField(choices=[('Yes', True), ('No', False)])),
                ('need_checkin', models.CharField(choices=[('Yes, by text', 'Yes, by text'), ('Yes, by phone', 'Yes, by phone'), ('No, thank you', 'No, thank you')], max_length=150)),
                ('extra_info', models.TextField(max_length=1024)),
                ('ma_pod_setup', models.CharField(max_length=150)),
                ('offer_resources', models.TextField(blank=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
