# Generated by Django 3.0.7 on 2020-06-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='contact_preference',
            field=models.CharField(choices=[('CALL', 'Phone Number - Call'), ('TEXT', 'Phone Number - Text'), ('EMAIL', 'Email')], max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='ma_pod_setup',
            field=models.CharField(choices=[], max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='share_info',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='urgency',
            field=models.CharField(choices=[('In the next 72 hours', 'In the next 72 hours'), ('Over the next few days', 'Over the next few days'), ('Useful if available', 'Useful if avaiable')], max_length=150),
        ),
    ]
