# Generated by Django 3.0.7 on 2020-06-29 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed'), ('Transferred', 'Transferred')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='ma_pod_setup',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], max_length=150),
        ),
    ]
