# Generated by Django 3.0.7 on 2020-08-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20200731_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
