# Generated by Django 3.0.7 on 2020-06-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20200629_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='extra_info',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='request',
            name='ma_pod_setup',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], max_length=150),
        ),
    ]
