# Generated by Django 3.0.7 on 2020-08-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20200824_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='address1',
            field=models.CharField(max_length=1024, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='request',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='request',
            name='household_number',
            field=models.SmallIntegerField(default=1, verbose_name='Family Size'),
        ),
        migrations.AlterField(
            model_name='request',
            name='last_edit',
            field=models.CharField(max_length=150, verbose_name='Last edit by'),
        ),
        migrations.AlterField(
            model_name='request',
            name='locations',
            field=models.CharField(choices=[('Algona Pacific', 'Algona Pacific'), ('Auburn', 'Auburn'), ('Bellevue', 'Bellevue'), ('Bothell', 'Bothell'), ('Burien', 'Burien'), ('Carnation', 'Carnation'), ('Covington', 'Covington'), ('Des Moines', 'Des Moines'), ('Duvall', 'Duvall'), ('Fall City', 'Fall City'), ('Federal Way', 'Federal Way'), ('High Line', 'High Line'), ('Issaquah', 'Issaquah'), ('Kenmore', 'Kenmore'), ('Kent', 'Kent'), ('Kirkland', 'Kirkland'), ('Maple Valley', 'Maple Valley'), ('Newcastle', 'Newcastle'), ('Normandy Park', 'Normandy Park'), ('North Bend', 'North Bend'), ('Puyallup', 'Puyallup'), ('Redmond', 'Redmond'), ('Renton', 'Renton'), ('Sammamish', 'Sammamish'), ('SeaTac', 'SeaTac'), ('Snoqualmie', 'Snoqualmie'), ('Sumner', 'Sumner'), ('Tukwila', 'Tukwila'), ('White Center', 'White Center'), ('Woodinville', 'Woodinville')], max_length=1024, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='request',
            name='volunteer_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=150, verbose_name='Support Status'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Support ID'),
        ),
    ]
