# Generated by Django 3.0.7 on 2020-06-30 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20200629_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='last_edit',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='offer_resources',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
