# Generated by Django 3.0.7 on 2020-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_auto_20200714_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='contact_preference',
            field=models.CharField(choices=[('Phone Number - Call', 'Phone Number - Call'), ('Phone Number - Text', 'Phone Number - Text'), ('Email', 'Email')], max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='financial_support',
            field=models.CharField(choices=[('Pay with your own money and donate to support your community members', 'Pay with your own money and donate to support your community members'), ('Pay with your own money (coordinate with delivery person)', 'Pay with your own money (coordinate with delivery person)'), ('Request support with your delivery items', 'Request support with your delivery items')], max_length=150),
        ),
    ]
