# Generated by Django 3.0.7 on 2020-09-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_auto_20200903_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='skip_reimbursement',
            field=models.BooleanField(default=False),
        ),
    ]
