# Generated by Django 3.0.7 on 2020-10-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_auto_20200930_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='agree_transfer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
            preserve_default=False,
        ),
    ]
