# Generated by Django 3.0.7 on 2020-10-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_request_agree_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=22),
        ),
    ]
